### ISSUE TITLE
Ambiguity in documentation about verb blocks

### ISSUE THREAD

**Issue by Pseudavid** [robindouglasjohnson/gruescript#13]
The doc says, regarding verb blocks (I add bold text):

Line 1523:

> When the player clicks on a verb next to an object, Gruescript will first look for specific verb blocks definitions matching that verb for that object, and then for general definitions of the verb. Gruescript then goes through each of those definitions in turn, running their instructions, until any one block succeeds. **Specific verb blocks are always processed before general verb blocks**.

Line 1582:

> If Gruescript finds multiple verb blocks that match the player's command, it will run through them all **(general first, then specific)** until one succeeds, then stop.

I'm unable to understand what the bolded sentences can mean together. Is this an ambiguity or a contradiction?

**Comment by robindouglasjohnson** [comment]
Good spot - it's a mistake in the documentation. It's always specific first, then general.

**Comment by robindouglasjohnson** [comment]
fixed in the latest commit.
