### ISSUE TITLE
Using dir to create unconventional directions doesn't seem to work

### ISSUE THREAD

**Issue by JJGUEST** [robindouglasjohnson/gruescript#2]
Hi Robin,

It says in the documentation that unconventional room directions can be created with dir:

brass_bridge You’re on the Brass Bridge.
dir widdershins patricians_palace
dir turnwise broad_way

This doesn't seem to do anything for me, at least, the directions don't appear under the room description.

- Jason

**Comment by robindouglasjohnson** [comment]
Thanks! They were actually being put into the data structure, but the buttons weren't being drawn. Fixed as of the commit I'm about to push.
