### ISSUE TITLE
Feature request: Gruescript docs in text format 

### ISSUE THREAD

**Issue by triptych** [robindouglasjohnson/gruescript#3]
Having the Gruescript docs in a format readable by a browser / editor would be cool - like say markdown or just plain text.

**Comment by robindouglasjohnson** [comment]
Thanks. I'm working on a markdown version.

**Comment by robindouglasjohnson** [comment]
There's now a markdown version of the manual: docs/gruescript.md

This will probably become the better maintained version, though I like having a nicely PDF-able manual with a silly cover too.
