### ISSUE TITLE
Instructions prompt undefined

### ISSUE THREAD

**Issue by delacannon** [robindouglasjohnson/gruescript#5]
Hey! I was trying out Gruescript. It's a very cool tool!

I noticed that when the initial instruction button is pressed, the prompt > appears as undefined. It seems that the text `Localise.instructions_button` is not set anymore. I used `Localise.intro_instructions_button` on the instruction function and works fine.

**Comment by robindouglasjohnson** [comment]
Thanks! I've fixed that as of the latest commit.
