### ISSUE TITLE
Cloak of Darkness example

### ISSUE THREAD

**Issue by delacannon** [robindouglasjohnson/gruescript#7]
Hi! While testing for a project I noticed that the Cloak of Darkness example has a small bug; you can drop the cloak on the floor in the first room then go south and win.

By adding this procedure it works fine!

```
proc check_bar
!has cloak hooked
tag bar dark
```

**Comment by robindouglasjohnson** [comment]
Hmm, I always thought that was working as designed - it's the cloak that causes the darkness. From the Cloak of Darkness spec (http://www.firthworks.com/roger/cloak/):

> Taking an inventory of possessions reveals that the player is wearing a black velvet cloak which, upon examination, is found to be light-absorbent. The player can drop the cloak on the floor of the Cloakroom or, better, put it on the hook.
> Returning to the Bar without the cloak reveals that the room is now lit. A message is scratched in the sawdust on the floor.

which isn't quite clear - the cloak doesn't seem to need to be on the hook, but it also doesn't mention dropping the cloak somewhere other than the cloakroom. I suppose a believable solution would be to intercept "drop cloak" to stop the player doing that ("It's too valuable to just sling on the floor!"), so they can't get rid of it except by hanging it up.

**Comment by delacannon** [comment]
Oops, yes, I see it now! I always thought the hook worked as a switch to turn on the light. Sorry for the misunderstanding.
