### ISSUE TITLE
Trouble including hash symbols in text

### ISSUE THREAD

**Issue by dmyates** [robindouglasjohnson/gruescript#9]
I'm experiencing some difficulty including literal #s in game text. As per the manual, I've used `&num;`, but I'm seeing the following:

- If I include `&num;` in the game title, the literal text `&NUM;` is displayed.
- If I include `&num;` elsewhere in displayed text, `#` shows up as expected while working with the game in the Gruescript editor, but as soon as I export the game to HTML, any text following a `&num;` does not display, as though `&num;` is being interpreted as a comment symbol.

I'm using the Gruescript editor on your itch.io page.

Thanks for building Gruescript, I'm having a lot of fun with it!

**Comment by robindouglasjohnson** [comment]
Thanks for this (and for your patience - I've had a lot going on.)
I believe this is all fixed as of the latest commit. Glad you're having fun!
